# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo.Token'),
        ),
    ]
